import { Button_Configuration_Map } from "../Types";

export const Default_Button_Configuration: Button_Configuration_Map = {
  Light: {
    Primary: {
      Default: {
        BG_Color: "#ffffff",
        Text_Color: "#0f172a",
        Border_Radius: 28,
        Has_Border: false,
        Border_Color: "transparent",

        Gooey: {
          Enabled: false,
          Blur: 5,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Rest_Outline_Amplitude: 0.4,
        },
        Padding: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Hover: {
        BG_Color: "#ffffff",
        Text_Color: "#0f172a",
        Border_Radius: 28,
        Has_Border: false,
        Border_Color: "transparent",
        Gooey: {
          Enabled: true,
          Blur: 5,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Rest_Outline_Amplitude: 0.4,
          Scale_Breathe_Amplitude: 0.02,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Hover_Splash_Min: 2,
          Hover_Splash_Max: 4,
          Hover_Splash_Intensity: 0.8,
          Release_Splash_Min: 1,
          Release_Splash_Max: 2,
          Release_Splash_Intensity: 0.6,
        },
        Padding: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Active: {
        BG_Color: "#ffffff",
        Text_Color: "#0f172a",
        Border_Radius: 28,
        Has_Border: false,
        Border_Color: "transparent",
        Gooey: {
          Enabled: true,
          Blur: 5,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Press_Scale_X: 1.08,
          Press_Scale_Y: 0.88,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Press_Splash_Min: 4,
          Press_Splash_Max: 7,
          Press_Splash_Intensity: 1.8,
        },
        Padding: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
    },
    Secondary: {
      Default: {
        BG_Color: "#f1f5f9",
        Text_Color: "#0f172a",
        Border_Radius: 12,
        Has_Border: false,
        Border_Color: "#e2e8f0",
        Gooey: {
          Enabled: false,
          Blur: 10,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Rest_Outline_Amplitude: 0.4,
        },
        Padding: { Top: 12, Right: 16, Bottom: 12, Left: 16 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Hover: {
        BG_Color: "#e2e8f0",
        Text_Color: "#0f172a",
        Border_Radius: 12,
        Has_Border: false,
        Border_Color: "#cbd5e1",
        Gooey: {
          Enabled: true,
          Blur: 10,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Rest_Outline_Amplitude: 0.4,
          Scale_Breathe_Amplitude: 0.02,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Hover_Splash_Min: 2,
          Hover_Splash_Max: 4,
          Hover_Splash_Intensity: 0.8,
          Release_Splash_Min: 1,
          Release_Splash_Max: 2,
          Release_Splash_Intensity: 0.6,
        },
        Padding: { Top: 12, Right: 16, Bottom: 12, Left: 16 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Active: {
        BG_Color: "#cbd5e1",
        Text_Color: "#0f172a",
        Border_Radius: 12,
        Has_Border: false,
        Border_Color: "#94a3b8",
        Gooey: {
          Enabled: true,
          Blur: 10,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Press_Scale_X: 1.08,
          Press_Scale_Y: 0.88,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Press_Splash_Min: 4,
          Press_Splash_Max: 7,
          Press_Splash_Intensity: 1.8,
        },
        Padding: { Top: 12, Right: 16, Bottom: 12, Left: 16 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
    },
  },
  Dark: {
    Primary: {
      Default: {
        BG_Color: "#ffffff",
        Text_Color: "#0f172a",
        Border_Radius: 28,
        Has_Border: false,
        Border_Color: "transparent",
        Gooey: {
          Enabled: true,
          Blur: 5,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Rest_Outline_Amplitude: 0.4,
        },
        Padding: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Hover: {
        BG_Color: "#ffffff",
        Text_Color: "#0f172a",
        Border_Radius: 28,
        Has_Border: false,
        Border_Color: "transparent",
        Gooey: {
          Enabled: true,
          Blur: 5,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Rest_Outline_Amplitude: 0.4,
          Scale_Breathe_Amplitude: 0.02,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Hover_Splash_Min: 2,
          Hover_Splash_Max: 4,
          Hover_Splash_Intensity: 0.8,
          Release_Splash_Min: 1,
          Release_Splash_Max: 2,
          Release_Splash_Intensity: 0.6,
        },
        Padding: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Active: {
        BG_Color: "#ffffff",
        Text_Color: "#0f172a",
        Border_Radius: 28,
        Has_Border: false,
        Border_Color: "transparent",
        Gooey: {
          Enabled: true,
          Blur: 5,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Press_Scale_X: 1.08,
          Press_Scale_Y: 0.88,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Press_Splash_Min: 4,
          Press_Splash_Max: 7,
          Press_Splash_Intensity: 1.8,
        },
        Padding: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
    },
    Secondary: {
      Default: {
        BG_Color: "#1e293b",
        Text_Color: "#f8fafc",
        Border_Radius: 12,
        Has_Border: false,
        Border_Color: "#334155",
        Gooey: {
          Enabled: false,
          Blur: 10,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Rest_Outline_Amplitude: 0.4,
        },
        Padding: { Top: 12, Right: 16, Bottom: 12, Left: 16 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Hover: {
        BG_Color: "#334155",
        Text_Color: "#f8fafc",
        Border_Radius: 12,
        Has_Border: false,
        Border_Color: "#475569",
        Gooey: {
          Enabled: true,
          Blur: 10,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Rest_Outline_Amplitude: 0.4,
          Scale_Breathe_Amplitude: 0.02,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Hover_Splash_Min: 2,
          Hover_Splash_Max: 4,
          Hover_Splash_Intensity: 0.8,
          Release_Splash_Min: 1,
          Release_Splash_Max: 2,
          Release_Splash_Intensity: 0.6,
        },
        Padding: { Top: 12, Right: 16, Bottom: 12, Left: 16 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
      Active: {
        BG_Color: "#475569",
        Text_Color: "#f8fafc",
        Border_Radius: 12,
        Has_Border: false,
        Border_Color: "#64748b",
        Gooey: {
          Enabled: true,
          Blur: 10,
          Contrast: 19,
          Canvas_Padding: 30,
          Draw_Body: true,
          Wave_Frequency: 0.05,
          Spring_Stiffness: 0.15,
          Spring_Damping: 0.75,
          Wave_Amplitude: 2.5,
          Press_Scale_X: 1.08,
          Press_Scale_Y: 0.88,
          Friction: 0.88,
          Attraction: 0.03,
          Attraction_Jitter: 0.02,
          Droplet_Min_Radius: 4,
          Droplet_Max_Radius: 14,
          Press_Splash_Min: 4,
          Press_Splash_Max: 7,
          Press_Splash_Intensity: 1.8,
        },
        Padding: { Top: 12, Right: 16, Bottom: 12, Left: 16 },
        Margin: { Top: 0, Right: 0, Bottom: 0, Left: 0 },
      },
    },
  },
};